### ISSUE TITLE
Add TXT description to GRPC errors

### ISSUE THREAD

**Issue by tomjad** [techmo-pl/tribune-client#4]
`Tribune TTS gRPC client 1.0.0
Synthesize RPC failed with status 12 `

Print also txt description of GRPC Status other than OK

**Comment by paweljaciow** [comment]
Doing in: https://github.com/techmo-pl/tribune-client/tree/2-grpc-status-codes-to-string

**Comment by paweljaciow** [comment]
Done: https://github.com/techmo-pl/tribune-client/pull/5
